# Generated by Django 4.2 on 2023-04-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_value', models.CharField(max_length=20, verbose_name='Narxi')),
                ('pc_description', models.CharField(max_length=200, verbose_name='Tasnifi')),
            ],
            options={
                'verbose_name': 'Narx',
                'verbose_name_plural': 'Narxlar',
            },
        ),
        migrations.CreateModel(
            name='PriceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pt_title', models.CharField(max_length=200, verbose_name="Xizmat ko'rsatish")),
                ('pt_old_price', models.CharField(max_length=200, verbose_name='Eski narx')),
                ('pt_new_price', models.CharField(max_length=200, verbose_name='Yangi narx')),
            ],
            options={
                'verbose_name': "Xizmat ko'rsatish",
                'verbose_name_plural': "Xizmat ko'rsatishlar",
            },
        ),
    ]
