# Generated by Django 4.2 on 2023-04-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_token', models.CharField(max_length=200, verbose_name='Token')),
                ('tg_chat', models.CharField(max_length=200, verbose_name='Chat id')),
                ('tg_message', models.TextField(verbose_name='Habar matni')),
            ],
            options={
                'verbose_name': 'Sozlama',
                'verbose_name_plural': 'Sozlamalar',
            },
        ),
    ]
