# Generated by Django 4.2 on 2023-04-12 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsCrm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(verbose_name='Komentariya matni')),
                ('comment_dt', models.DateTimeField(auto_now=True, verbose_name='Yaratilga vaqti')),
                ('comment_binding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.order', verbose_name='Buyurtma')),
            ],
            options={
                'verbose_name': 'Komentariya',
                'verbose_name_plural': 'Komentariyalar',
            },
        ),
    ]
